import type { Metadata } from "next";
import { Inter, Cairo } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["latin", "arabic"], weight: ["400", "700"] }); // إضافة الخط العربي

export const metadata: Metadata = {
  title: "Create Url App",
  description: "Generated by create url app",
  openGraph: {
    title: "Create Url App",
    description: "Generated by create url app",
    images: "/abc.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className={`${inter.className} ${cairo.className}`}>
        {children}
      </body>
    </html>
  );
}
